name: Build APK

on:
  push:
    branches:
      - main  # ajusta el nombre de la rama según tu configuración

jobs:
  build:
    runs-on: ubuntu-latest  # usa el sistema operativo adecuado, como ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # ajusta según tu versión de Python

      - name: Install Buildozer and Dependencies
        run: |
          pip install buildozer
          sudo apt-get install -y python3-pip python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK Artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: myapp-debug
          path: bin/*.apk  # ajusta la ruta del archivo APK generado
